import { Link } from 'react-router-dom';
import { Zap, Flame, Target, Crosshair, BookOpen, Check, Clock3, Sparkles, Trophy, CircleHelp, ChevronRight, Play } from 'lucide-react';
import { useProgress } from '../context/ProgressContext.jsx';
import { getSummary, nextGroup, jakartaDate, getStatus } from '../lib/progress.js';
import { groups, groupById } from '../data/kana.js';
import { ProgressBar, SectionHeading } from '../components/ui.jsx';

export default function Dashboard() {
  const {state}=useProgress();
  const summary=getSummary(state), group=nextGroup(state);
  const today=state.daily[jakartaDate()]??{answers:0,groups:[]};
  const learned=group.kana.filter(k=>state.kana[k.id].introduced).length;
  const first=summary.learnedTotal===0;
  return <div className="page-enter">
    <div className="welcome-row"><div><p className="eyebrow">PERJALANANMU DIMULAI DARI SINI</p><h1>Selamat datang, Playful<span className="welcome-spark">✦</span></h1><p className="page-description">{first?'Siap mengenal huruf pertamamu? Mari mulai pelan-pelan.':'Lanjutkan langkah kecilmu. Setiap latihan membawa kemajuan.'}</p></div><div className="learner-badge"><span><Sparkles size={18}/></span><div><small>LEVEL {summary.level}</small><strong>{summary.level<3?'Penjelajah Baru':'Penjelajah Hiragana'}</strong></div></div></div>
    <div className="stat-grid">
      <Stat icon={Zap} label="Total XP" value={state.xp} suffix="XP" color="purple" hint={`${100-summary.levelXp} XP menuju level ${summary.level+1}`}><ProgressBar value={summary.levelXp} label="Progres level"/></Stat>
      <Stat icon={Flame} label="Streak belajar" value={summary.streak} suffix="hari" color="orange" hint={summary.streak?'Teruskan kebiasaan baikmu':'Satu latihan untuk mulai streak'}/>
      <Stat icon={BookOpen} label="Kana dikuasai" value={summary.mastered} suffix="/ 46" color="cyan" hint={`${summary.learnedTotal} kana sudah dipelajari · ${summary.mastery}% dikuasai`}/>
      <Stat icon={Crosshair} label="Akurasi" value={summary.accuracy} suffix="%" color="green" hint={summary.attempts?`${summary.correct} benar dari ${summary.attempts} jawaban`:'Belum ada jawaban kuis'}/>
    </div>
    <div className="dashboard-main">
      <section className="study-feature"><div className="feature-content"><span className="feature-label"><span className="tiny-dot"/> {first?'PELAJARAN PERTAMA':'LANJUTKAN BELAJAR'}</span><h2>{first?'Awali dengan\nlima vokal.':`Jelajahi\n${group.name.toLowerCase()}.`}</h2><p>{first?'Kenali あ・い・う・え・お, fondasi untuk membaca bahasa Jepang.':group.description+' Pelajari setiap kartu, lalu uji ingatanmu.'}</p><div className="lesson-meta"><span><BookOpen size={15}/> {group.kana.length} karakter</span><span><Clock3 size={15}/> ± 5 menit</span></div><Link className="button primary" to={`/belajar/${group.id}`}><Play size={17} fill="currentColor"/> Mulai Belajar</Link><div className="feature-progress"><ProgressBar value={learned} max={group.kana.length} label="Progres kelompok berikutnya"/><span>{learned}/{group.kana.length} dikenali</span></div></div><div className="feature-kana" aria-hidden="true"><div className="floating-kana small top kana-font">{group.kana[1]?.character??'ん'}</div><div className="floating-kana main kana-font">{group.kana[0].character}<small>{group.kana[0].romaji}</small></div><div className="floating-kana small bottom kana-font">{group.kana[2]?.character??group.kana[0].character}</div><span className="kana-caption">HIRAGANA • {String(group.index+1).padStart(2,'0')}</span></div></section>
      <section className="card mission-card"><div className="mission-header"><span className="icon-tile purple"><Target size={21}/></span><div><h2>Misi hari ini</h2><p>Langkah kecil, setiap hari</p></div></div><div className="mission-row"><span className={`mission-check ${today.groups.length?'done':''}`}>{today.groups.length?<Check size={16}/>:<BookOpen size={16}/>}</span><div><strong>Kenali satu kelompok baru</strong><p>{today.groups.length?'Misi selesai. Kerja bagus!':`Mulai dari ${group.name.toLowerCase()}`}</p></div><span>{Math.min(today.groups.length,1)}/1</span></div><div className="mission-row"><span className={`mission-check ${today.answers>=10?'done':''}`}>{today.answers>=10?<Check size={16}/>:<Crosshair size={16}/>}</span><div><strong>Jawab 10 soal latihan</strong><p>Asah ingatan hiraganamu</p></div><span>{Math.min(today.answers,10)}/10</span></div><ProgressBar value={((today.groups.length?1:0)+Math.min(today.answers/10,1))*50} label="Progres misi harian"/><p className="mission-foot"><Zap size={14}/> XP bertambah dari belajar & jawabanmu</p></section>
    </div>
    <div className="dashboard-bottom"><section><SectionHeading title="Peta perjalananmu"><Link className="text-link" to="/hiragana">Lihat semua <ChevronRight size={16}/></Link></SectionHeading><div className="journey-groups">{groups.slice(0,3).map((g,i)=>{const count=g.kana.filter(k=>getStatus(state.kana[k.id])!=='new').length;return <Link className={`journey-card ${group.id===g.id?'current':''}`} key={g.id} to={`/belajar/${g.id}`}><div className="journey-top"><span className="group-number">{String(i+1).padStart(2,'0')}</span><span>{count===g.kana.length?'Dipelajari':group.id===g.id?'Mulai di sini':'Berikutnya'}</span></div><div className="journey-characters kana-font">{g.kana.map(k=>k.character).join(' ')}</div><strong>{g.name}</strong><ProgressBar value={count} max={g.kana.length} label={`Progres ${g.name}`}/><small>{count}/{g.kana.length} kana dipelajari</small></Link>;})}</div><section className="review-banner"><div className="icon-tile cyan"><Target size={23}/></div><div><h3>Sedikit sulit? Latih lagi.</h3><p>Latihan yang menyesuaikan huruf yang perlu kamu ulang.</p></div><Link className="button secondary small-button" to="/kuis/adaptive">Latihan Huruf Sulit</Link></section></section>
      <section className="card activity-card"><SectionHeading title="Aktivitas terakhir"><Clock3 size={18} className="muted"/></SectionHeading>{!state.history.length?<div className="activity-empty"><span className="activity-empty-icon"><BookOpen size={27}/></span><h3>Cerita belajarmu dimulai hari ini</h3><p>Selesaikan pelajaran atau kuis pertama untuk melihat aktivitasmu di sini.</p><span className="mini-prompt">いっしょに、はじめよう。<br/><small>Mari mulai bersama.</small></span></div>:<div className="activity-list">{state.history.slice(0,3).map(h=><div className="activity-item" key={h.id}><span className={`icon-tile ${h.type==='quiz'?'purple':'cyan'}`}>{h.type==='quiz'?<Trophy size={17}/>:<BookOpen size={17}/>}</span><div><strong>{h.type==='quiz'?`Kuis · ${h.score}/10 benar`:`Belajar ${groupById[h.groupId].name}`}</strong><small>{formatDate(h.date)}</small></div>{h.type==='quiz'&&<span className="xp-earned">+{h.xp} XP</span>}</div>)}</div>}</section>
    </div><div className="daily-thought"><span className="kana-font">一歩ずつ</span><p>Selangkah demi selangkah. Kamu tidak harus cepat, cukup terus melangkah.</p></div>
  </div>;
}
function Stat({icon:Icon,label,value,suffix,color,hint,children}) {return <section className="card stat-card"><div className="stat-top"><span>{label}</span><Icon size={18} className={`text-${color}`}/></div><div className="stat-value">{value}<span>{suffix}</span></div>{children}<p>{hint}</p></section>;}
export const formatDate = date=>new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Jakarta',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(date));
