import { Link } from 'react-router-dom';
import { ChartNoAxesCombined, BookOpen, Trophy, Target } from 'lucide-react';
import { useProgress } from '../context/ProgressContext.jsx';
import { kana, groups, groupById } from '../data/kana.js';
import { getSummary, getStatus, getAccuracy } from '../lib/progress.js';
import { PageTitle, SectionHeading, ProgressBar, EmptyState } from '../components/ui.jsx';
import { formatDate } from './Dashboard.jsx';

export default function Progress() {
  const {state}=useProgress(), summary=getSummary(state);
  const practiced=kana.filter(k=>state.kana[k.id].attempts>0).sort((a,b)=>state.kana[a.id].correct/state.kana[a.id].attempts-state.kana[b.id].correct/state.kana[b.id].attempts || state.kana[b.id].attempts-state.kana[a.id].attempts);
  return <div className="page-enter"><PageTitle eyebrow="SETIAP LANGKAH TERCATAT" title="Progres Saya" description="Lihat apa yang sudah kamu pelajari dan arah langkah berikutnya."/>
    <div className="progress-overview"><section className="card mastery-card"><div className="mastery-ring" style={{'--progress':`${summary.mastery}%`}}><div><strong>{summary.mastery}<small>%</small></strong><span>penguasaan</span></div></div><div><h2>Hiragana dasar</h2><p>{summary.mastered} dari 46 kana dikuasai</p><div className="status-counts"><span><i className="new"/>Baru <strong>{summary.new}</strong></span><span><i className="learned"/>Dipelajari <strong>{summary.learned}</strong></span><span><i className="mastered"/>Dikuasai <strong>{summary.mastered}</strong></span></div></div></section><section className="card accuracy-card"><span className="icon-tile cyan"><Target size={21}/></span><h2>Akurasi keseluruhan</h2><strong>{summary.accuracy}<small>%</small></strong><p>{summary.attempts?`${summary.correct} jawaban benar dari ${summary.attempts} jawaban`:'Belum ada jawaban. Mulai kuis pertamamu.'}</p></section></div>
    <div className="progress-columns"><section className="card group-progress-card"><SectionHeading title="Progres per kelompok"/><div className="group-progress-list">{groups.map(g=>{const mastered=g.kana.filter(k=>getStatus(state.kana[k.id])==='mastered').length,learned=g.kana.filter(k=>getStatus(state.kana[k.id])!=='new').length;return <Link key={g.id} to={`/belajar/${g.id}`} className="group-progress-row"><div><strong>{g.name}</strong><span>{mastered}/{g.kana.length} dikuasai</span></div><ProgressBar value={mastered} max={g.kana.length} label={`Penguasaan ${g.name}`}/><small>{g.kana.map(k=>k.character).join(' ・ ')} <span>· {learned} dipelajari</span></small></Link>;})}</div></section><div><section className="card strengths-card"><SectionHeading title="Dari riwayat latihanmu"/>{practiced.length?<><KanaHighlight label="Perlu perhatian" item={practiced[0]} stats={state.kana[practiced[0].id]} color="orange"/><KanaHighlight label="Paling kuat" item={practiced.at(-1)} stats={state.kana[practiced.at(-1).id]} color="cyan"/></>:<div className="small-empty"><ChartNoAxesCombined size={29}/><p>Huruf terkuat dan terlemah akan terlihat setelah kuis pertamamu.</p></div>}</section><section className="card history-card"><SectionHeading title="Riwayat belajar"/>{!state.history.length?<div className="small-empty"><BookOpen size={27}/><p>Belum ada sesi selesai. Pelajaran pertamamu menunggu.</p><Link className="text-link" to="/belajar/vowels">Mulai belajar vokal</Link></div>:<div className="history-list">{state.history.map(h=><div className="history-item" key={h.id}><span className={`icon-tile ${h.type==='quiz'?'purple':'cyan'}`}>{h.type==='quiz'?<Trophy size={18}/>:<BookOpen size={18}/>}</span><div><strong>{h.type==='lesson'?`Belajar ${groupById[h.groupId].name}`:h.mode==='group'?`Kuis ${groupById[h.groupId].name}`:h.mode==='adaptive'?'Latihan adaptif':'Latihan umum'}</strong><small>{formatDate(h.date)}</small>{h.type==='quiz'&&<Link to={`/hasil/${h.id}`} className="text-link">{h.score}/10 benar · Lihat hasil</Link>}</div>{h.type==='quiz'&&<span className="xp-earned">+{h.xp} XP</span>}</div>)}</div>}</section></div></div><p className="helper-text">Penguasaan dihitung dari minimal 5 jawaban per huruf dan akurasi minimal 80%. Status dapat berubah mengikuti jawaban terbaru.</p>
  </div>;
}
function KanaHighlight({label,item,stats,color}) {return <Link className="kana-highlight" to={`/belajar/${item.group}?kana=${item.id}`}><span className={`highlight-character kana-font text-${color}`}>{item.character}</span><div><small>{label}</small><strong>{item.romaji}</strong><p>{getAccuracy(stats)}% akurasi · {stats.attempts} jawaban</p></div></Link>;}
